### PR TITLE
CDM_conversion code needs to include compression on output

### LINKED ISSUE #65: CDM_conversion code for sub-daily needs to output .gz files to save disc space
The cdm_conversion code for the sub-daily lite, header, qc,and observations tables needs to output .psv.gsz files, it curnetly does not zip them up.

### PR DESCRIPTION
**Pull request by rjhd2**
Closes #65

### CODE REVIEW

**Review by sjnoone — COMMENTED** [review]
we need to check if the qff will be .gz

**Comment by rjhd2** [comment]
> we need to check if the qff will be .gz

True - it's not currently set up to be.  Would be an easy change to update though, now. Do we know if the mff's will be too?

**Comment by sjnoone** [comment]
I think we should amke sure that the qff are compressed and I can check with Matt on the mff either way I can compress the mff after they are produced if needs be , Make sense to zip them up saves space.

**Comment by rjhd2** [comment]
OK.  I can make that edit on my QC code for the qffs (both sets).  If the mff changes, then my code will also need to know about that so that it can find the files.

**Comment by sjnoone** [comment]
ok cool, I will send Matt an email but will remind him for next run. Thanks.

**Review by sjnoone — APPROVED** [review]
thanks

**Pull request merged**
